### ISSUE TITLE
请问HTTP函数的公网访问地址在哪里获取呢

### ISSUE THREAD

**Issue by yangchao4** [Sunny-Law/Dingtalk-ChatGPT-Connector#3]
![image](https://user-images.githubusercontent.com/35161311/227610720-af38c85d-6b50-46cb-8738-2ce84540d7eb.png)
是这三个中的一个吗

**Comment by Sunny-Law** [comment]
> ![image](https://user-images.githubusercontent.com/35161311/227610720-af38c85d-6b50-46cb-8738-2ce84540d7eb.png) 是这三个中的一个吗

是的，第一个公网访问地址就是

**Comment by yangchao4** [comment]
非常感觉
